- plugins/synology-ss/.gitignore
- plugins/synology-ss/.npmignore
- plugins/synology-ss/.vscode/launch.json
- plugins/synology-ss/.vscode/settings.json
- plugins/synology-ss/.vscode/tasks.json
- plugins/synology-ss/README.md
- plugins/synology-ss/package-lock.json
- plugins/synology-ss/package.json
- plugins/synology-ss/src/api/synology-api-client.ts
- plugins/synology-ss/src/main.ts
Creating a PR for initial review. Let me know how it looks! Planning on working on motion detection functionality next.
CC @koush
> Plugin for Synology Surveillance Station

- plugins/homekit/src/types/thermostat.ts
Update HomeKit thermostat type to support temperature range in auto mode
> thermostat: support thermostat range

- plugins/ecobee/ .npmignore
- plugins/ecobee/.gitignore
- plugins/ecobee/.vscode/launch.json
- plugins/ecobee/.vscode/settings.json
- plugins/ecobee/.vscode/tasks.json
- plugins/ecobee/README.md
- plugins/ecobee/package-lock.json
- plugins/ecobee/package.json
- plugins/ecobee/src/main.ts
Mostly complete with a few work in progress items:
- Support getCode/getToken from UI
- UI buttons to enable/disable separate humidify/fan control in HomeKit
- Cleanup extraneous logging into "debug" UI option
> Ecobee plugin

- plugins/hikvision/src/hikvision-camera-api.ts
- plugins/hikvision/src/main.ts
As per discussion on Discord, with the older Hikvision NVR (DS-7608NI-E2/8P) the system can stop processing new requests when 1) receiving requests it doesn't support (/ISAPI/Streaming/channels and Streaming/channels/CAM/capabilities) and 2) when receiving too many concurrent notification/alertStream requests.
These changes address this by:
1) Checking the deviceModel of the NVR and bypassing the unsupported requests (using the existing defaults)
2) Finishing the support for using a shared HikVisionCameraAPI with a single request stream in listenEvents().
> Support for old Hikvision NVR by suppressing unsupported requests and limiting number of alert streams

- plugins/amcrest/src/main.ts
The new function should get device manufacturer, serial number, firmware and model. 
I am not sure if the function is called at the right moment but it seems to be working fine for my Dahua camera, its info is displayed in the Home app.
> Dahua/Amcrest Device Info

- plugins/ring/src/main.ts
Added option to only show specific locationIds
Added option to set cameraDingsPollingSeconds
Added firmware info
Added serialNumber info.
Added Intercom to all devices.
> Multiple Enhancments

- README.md
Added an installation guide for QNAP NAS installations via docker/Container Station
> QNAP Installation Guide

- plugins/homekit/src/types/sensor.ts
Add FloodSensor type to Sensor in HomeKit
> homekit: add flood sensor

- plugins/synology-ss/src/api/synology-api-client.ts
- plugins/synology-ss/src/main.ts
Support for sub-streams by using cameras native streams when necessary.
> synology-ss: support for sub streams

- plugins/ecobee/package.json
- plugins/ecobee/src/main.ts
Stop setting device.info, implement setThermometerUnit, publish v0.0.16
> ecobee: fix device.info

- plugins/homekit/package-lock.json
- plugins/homekit/src/types/sensor.ts
Add support for Air Quality Sensor with Air Quality, VOC, and PM2.5 values
> homekit: add support for Air Quality Sensor

- plugins/zwave/src/CommandClasses/ZwaveDeviceBase.ts
- plugins/zwave/src/main.ts
- listen for statistics messages and display latest for each node
- display various node information
- display various controller information
- add "refreshInfo" button to refresh all node info
> zwave: additional menu options

- plugins/homekit/src/types/index.ts
- plugins/homekit/src/types/security.ts
Adds support for security system in HomeKit
> homekit: add security system type

- plugins/homekit/src/types/sensor.ts
- plugins/homekit/src/types/thermostat.ts
Adds CO2 sensor, with "CO2 detected" when PPM is greater than 5000
> homekit: add co2sensor

- README.md
HomeKit Secure Video Support was redirecting to a non existent section
> fixed URL not redirecting

- plugins/google-device-access/README.md
New step by step guide for how to get Google Device Access working
> Updated README for Google Device Access

- plugins/homekit/src/types/light.ts
> Implement ColorSettingTemperature in HomeKit plugin

- plugins/tuya/README.md
- plugins/tuya/package.json
- plugins/tuya/src/camera.ts
- plugins/tuya/src/main.ts
- plugins/tuya/src/tuya/cloud.ts
Hello again,
There was an issue with Tuya devices and Scrypted with race conditions. This update fixes that issue and I also updated the `Development.md` file due to a mistype.
I also increased the version in `package.json` to 0.0.4.
> Fix race condition for Tuya Devices

- plugins/tuya/README.md
- plugins/tuya/package-lock.json
- plugins/tuya/package.json
- plugins/tuya/src/camera.ts
- plugins/tuya/src/main.ts
- plugins/tuya/src/tuya/cloud.ts
- plugins/tuya/src/tuya/device.ts
- plugins/tuya/src/tuya/pulsar.ts
Hello,
This pull request fixes issues where users are unable to view or change anything in regards to their devices due to Race condition that have been fixed now. I also added requirements in order to get everything working well with Tuya's Cloud API and this plug in.
I will be implementing WebRTC for 2 way audio and doorbell support next.
> [Tuya Plugin] Fixed issue with devices not loading

- plugins/tuya/package-lock.json
- plugins/tuya/package.json
- plugins/tuya/src/camera.ts
- plugins/tuya/src/main.ts
- plugins/tuya/src/tuya/cloud.ts
- plugins/tuya/src/tuya/device.ts
Hello,
This update brings support for Tuya Camera Doorbell with ring notifications to scrypted.
- it also provides logs for future debugging.
- bump version to 0.0.6 as latest.
<del>FYI: there is a commit that somehow got inside this request so I will need to remove it later before accepting this pull request.</del>
Rebased and squashed which fixed the issue.
> [Tuya Plugin] Support Camera Doorbell Ring

- plugins/core/src/aggregate.ts
- plugins/homekit/src/types/sensor.ts
- sdk/gen/types.input.ts
- sdk/scrypted_python/scrypted_sdk/types.py
- sdk/types/index.d.ts
- sdk/types/index.js
- sdk/types/index.ts
- sdk/types/scrypted_python/scrypted_sdk/types.py
Added support for NOX and PM10 to the available sensors.
> Added `NOXSensor` and `PM10Sensor` for use

- plugins/arlo/package-lock.json
- plugins/arlo/package.json
- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/arlo/mqtt_stream_async.py
- plugins/arlo/src/arlo_plugin/arlo/request.py
- plugins/arlo/src/arlo_plugin/arlo/sse_stream_async.py
- plugins/arlo/src/arlo_plugin/arlo/stream_async.py
- plugins/arlo/src/arlo_plugin/doorbell.py
- plugins/arlo/src/arlo_plugin/provider.py
- plugins/arlo/src/requirements.txt
Doorbell events are not yet functional
> arlo: beta 0.3.1 w/ SSE, arloqs, and doorbell pings

- plugins/homekit/src/types/sensor.ts
- plugins/homekit/src/types/thermostat.ts
I missed a few sensor bindings when I originally pushed my commit
> updated the sensor bindings

- common/src/sdp-utils.ts
- plugins/bticino/.gitignore
- plugins/bticino/.npmignore
- plugins/bticino/.vscode/launch.json
- plugins/bticino/.vscode/settings.json
- plugins/bticino/.vscode/tasks.json
- plugins/bticino/README.md
- plugins/bticino/package-lock.json
- plugins/bticino/package.json
- plugins/bticino/src/main.ts
- plugins/bticino/src/sip-call.ts
- plugins/bticino/src/sip-session.ts
- plugins/bticino/tsconfig.json
Follow up of #463 - might extract some more code from sip-call an/or sip-session as I move on to audio out
> First working version for a BTicino C300X

- plugins/ring/README.md
I think there could be a lot more information about the Ring plugin in Readme.
I took most repeated questions from the Discord #Ring channel and wrote them here. 
It would definitely help me when I found Ring Plugin for Scrypted.
> Readme.md - Added information found in #Ring on Scrypted Discord

- plugins/alexa/README.md
The instructions for Alexa plugin are outdated, I have updated them to provide both instructions for the Alexa app and browser.
> Updated the installation instructions for Alexa plugin

- plugins/homekit/src/types/thermostat.ts
I'm submitting a PR for comment per the discussion on Discord.
At present, the HomeKit plugin supports the 'Heat', 'Cool' and 'Auto' modes for thermostats, and when 'Auto' mode is active separate heating and cooling thresholds are exposed for independent control by the user. However, not all thermostats support separate heating and cooling thresholds; in particular, thermostats integrated into split-system air conditioners often only support a single temperature setting even in 'Auto' mode. This PR changes the HomeKit plugin so that when the user selects the 'Auto' mode in the Home app, only one threshold is exposed - unless the 'HeatCool' thermostat mode is available on the Scrypted device.
Internally this is implemented by changing the behaviour of the HomeKit plugin. Before this PR:
- …
> RFC: Change handling of thermostat modes in HomeKit to separate 'Auto' and 'HeatCool' modes

- plugins/alexa/src/main.ts
Related to our discord conversation, I have added logging around `tokenInfo` resets to help track down issue reported.
> alexa: added logging around `tokenInfo` resets

- plugins/myq/src/main.ts
I was getting duplicate serial-number errors in the "HomeKit Controller" app.
> myq: added device info, and `Online` interface

- plugins/homekit/README.md
Took a while to figure out why my cameras were simply not recording and figured this may save someone else the headache in the future :)
> Additional HKSV troubleshooting tips

- plugins/ring/src/main.ts
Adding support for siren for ring cameras that have a siren.
Fixes #525 
@koush
> Adding support for siren

- plugins/ring/src/main.ts
As per:
https://github.com/koush/scrypted/pull/570#issuecomment-1439407593
> Using `Siren` type

- plugins/alexa/package.json
- plugins/alexa/src/main.ts
- plugins/alexa/src/types/camera.ts
**DO NOT MERGE**
I still need to do some targeted testing within the NA, EU, and FE regions.  However I am posting this for early access review to get more eyes on the change.
> alexa plugin: ensure we are talking to the right endpoint region for a customer

- plugins/alexa/package.json
- plugins/alexa/src/main.ts
- plugins/alexa/src/types/camera.ts
> Revert "alexa plugin: ensure we are talking to the right endpoint region for a customer"

- plugins/amcrest/src/amcrest-api.ts
- plugins/amcrest/src/main.ts
Found some errors after tested multiple times. Pls review now. Version of Amcrest plugin would need to be increased if this PR is accepted.
>  New DahuaEventType and introduction of CallerId for Dahua Intercoms with multiple Bell Buttons.

- plugins/unifi-protect/src/camera.ts
- plugins/unifi-protect/src/main.ts
* Added `smartDetectLine` as a trigger type
* Updated snapshot logic for events to use `fetchLogin`
> unifi-protect: added new smart event and updated snapshot to use login

- .gitmodules
- plugins/cloud/package-lock.json
- plugins/cloud/package.json
- plugins/ring/package-lock.json
- plugins/ring/package.json
* Update Ring Submodule to Fork Branch
* Remove Push-Receiver Submodule 🎉
> ring: update dependencies

- plugins/ring/README.md
- plugins/ring/package-lock.json
- plugins/ring/package.json
- plugins/ring/src/main.ts
someone asked for this on discord a while back
> ring: add support for locks

- plugins/ring/package-lock.json
- plugins/ring/package.json
- plugins/ring/src/main.ts
Phase 1 of restructure. Will do another PR to address splitting up `main.ts` into separate files.
> ring: restructure plugin

- plugins/ring/README.md
- plugins/ring/package-lock.json
- plugins/ring/package.json
- plugins/ring/src/location.ts
- Requested on discord. 
- No support in HomeKit for glass break sensor, so it's implemented as a contact sensor.
> ring: add glass break & mailbox sensor

- plugins/homekit/package-lock.json
- plugins/homekit/package.json
- plugins/homekit/src/types/camera.ts
Persistence is already handled in HAP-NodeJS: https://github.com/homebridge/HAP-NodeJS/blob/0655c18fc3ccc0637166ccfd915bf7aef0d2b14f/src/lib/camera/RecordingManagement.ts#LL348C31-L348C31
> hap: remove persistence from camera type

- plugins/alexa/package.json
- plugins/alexa/src/main.ts
added debug option, to allow for more verbose logging in the Alexa plugin to troubleshoot issues
> alexa: add setting to publish debug events to console

- npm-install.sh
- plugins/ring/package-lock.json
- plugins/ring/package.json
already pushed the new version of the plugin since it just required a version bump.
fixed npm-install.sh (unrelated to this)
> ring: fix login 406 error

- plugins/doorbird/.gitignore
- plugins/doorbird/.npmignore
- plugins/doorbird/.vscode/launch.json
- plugins/doorbird/.vscode/settings.json
- plugins/doorbird/.vscode/tasks.json
- plugins/doorbird/README.md
- plugins/doorbird/package-lock.json
- plugins/doorbird/package.json
- plugins/doorbird/src/doorbird-api.ts
- plugins/doorbird/src/main.ts
- plugins/doorbird/tsconfig.json
This is a new plugin for Doorbird video doorbell stations: https://www.doorbird.com/
The plugin will use the API that is documented by the manufacturer here: https://www.doorbird.com/downloads/api_lan.pdf
It will use this NPM module to receive doorbell and motion sensor events: https://github.com/ihrigb/node-doorbird
**WORKING:**
- receive video stream (720p @ 10 FPS) via unencrypted RTSP
- receive audio stream (8000 Hz, 1 channel, PCM uLaw) via unencrypted HTTP calls to audio-receive.cgi
- sending audio to the doorbell speaker via documented HTTP calls to audio-transmit.cgi endpoint.
- event handling for doorbell button and motion sensor using the existing NPM module (see above).
**TODO:**
- ~improve security by using session ID token via encrypted HTTPS calls to getsession.cgi and use …
> Initial version of Doorbird plugin

- plugins/arlo/package-lock.json
- plugins/arlo/package.json
- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/arlo/host_picker.py
- plugins/arlo/src/arlo_plugin/arlo/request.py
- plugins/arlo/src/arlo_plugin/provider.py
- plugins/arlo/src/requirements.txt
> arlo: backup code path for cloudflare 403

- plugins/arlo/README.md
- plugins/arlo/package-lock.json
- plugins/arlo/package.json
- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/arlo/request.py
- plugins/arlo/src/arlo_plugin/basestation.py
- plugins/arlo/src/arlo_plugin/camera.py
- plugins/arlo/src/requirements.txt
* Add printing of basestation debug info
* Improve startup latency for 2-way audio
* (beta) Skip pings for battery doorbell avd2001
* (beta) Use curl-cffi for cloudflare 403
> arlo: update to 0.8.4 beta

- .gitignore
- sdk/types/scrypted_python/scrypted_sdk/other.py
- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/build.ts
- sdk/types/src/types.input.ts
Adds stub references to typescript objects which are otherwise undefined, adds some formatting tweaks, and adds docstrings/comments
> Improve python generation

- plugins/alexa/package-lock.json
- plugins/alexa/package.json
- plugins/alexa/src/main.ts
- plugins/alexa/src/types/camera/handlers.ts
- plugins/alexa/tsconfig.json
Added an alert to help the user identify when they need to reauthenticate to fix a connection problem. In addition, I implemented the latest `RTCSignalingSession` interfaces in the SDK.
> alexa: added helpful error messages regarding token expiration

- plugins/chromecast/package-lock.json
- plugins/chromecast/package.json
Publishing on behalf of community members who wanted a fix released.
> chromecast: publish

- plugins/alexa/package-lock.json
- plugins/alexa/package.json
- plugins/alexa/src/types/camera/capabilities.ts
- plugins/alexa/src/types/camera/handlers.ts
- plugins/alexa/src/types/doorbell.ts
Fixed the issue where the doorbell camera wasn't being triggered when doorbell pressed.
> alexa: display camera on doorbell press

- sdk/bin/scrypted-webpack.js
Typical JS/TS plugins will use either `src/main.js` or `src/main.ts` as the entrypoint for the webpack bundle. For other languages (such as CoffeeScript), the file extensions may be different.
The scrypted-webpack script already supports per-plugin custom webpack config - this change extends the behavior to allow custom webpack config to also specify a different entrypoint if not already covered by the default options.
> sdk: configurable webpack entrypoint

- plugins/cloud/README.md
I ran into a few hiccups setting up port forwarding and would like to make the docs a little bit clearer on what steps to take and what to avoid.
> Docs: Update and simplify port forwarding guide for beginners

- server/python/rpc.py
`random.choices` will reduce the randomDigits alphabet to just 1 char
> server: fix python rpc id gen

- plugins/bticino/package-lock.json
- plugins/bticino/package.json
- plugins/bticino/src/bticino-aswm-switch.ts
- plugins/bticino/src/bticino-camera.ts
- plugins/bticino/src/bticino-voicemailHandler.ts
- plugins/bticino/src/c300x-controller-api.ts
- plugins/bticino/src/main.ts
Support turning on/off answering machine
> bticino: Support turning on/off ringer and answering machine

- plugins/tapo/src/tapo-api.ts
detect the new encrypt_type, if eq 3, use sha256 hashed
ref: 
issue: https://github.com/AlexxIT/go2rtc/issues/733
source_code: https://github.com/AlexxIT/go2rtc/commit/5d3953a9487e1ff528eed25467c59a83a8986cb5
> fix(tapo): new firmware v1.3.9 use sha256 hashed

- plugins/core/src/builtins/scheduler.ts
The previous scheduler's reschedule function did not schedule a timeout after the first event. This change ensures that the timeout is re-added once an event occurs.
> core: fix scheduler

- plugins/amcrest/src/main.ts
The intercom was not working with my VTO2000, so I dug into the problem and found out, that only G.711A is supported.
So if `Two Way Audio` is `Amcrest` and `Doorbell Type` is `Dahua Doorbell` G.711A is used instead of AAC.
> Implemented other intercom codec for Dahua doorbells (G.711A)

- plugins/synology-ss/package-lock.json
- plugins/synology-ss/package.json
- plugins/synology-ss/src/api/synology-api-client.ts
- plugins/synology-ss/src/main.ts
- plugins/synology-ss/tsconfig.json
> synology-ss: make login more resilient

- plugins/core/ui/src/components/builtin/ShellComponent.vue
Based on existing cli flow control implementation
> ui: add client-side flow control

- sdk/types/package-lock.json
- sdk/types/package.json
- sdk/types/tsconfig.json
> Revert "Add tsconfig strict to `sdk/types`"

- plugins/eufy/src/main.ts
- plugins/ring/src/main.ts
Spotted a typo in the Ring plugin, but it's also present for Eufy
> Fix typos (conplete => complete)

- plugins/alexa/package-lock.json
- plugins/alexa/package.json
removed `color-convert` from Alexa as it was no longer needed
> alexa: removed unneeded packages

- plugins/core/src/builtins/scheduler.ts
Some properties were added to fix compilation errors, I assume due to the recent strict sdk typing
> core: reset base date on each reschedule call

- server/python/plugin_repl.py
On Windows, the default asyncio event loop uses the ProactorEventLoop policy, which does not support `loop.add_reader()`, a function required by `ptpython`. To avoid changing loop defaults in the main Scrypted loop, this change isolates the REPL's loop in a separate thread and brokers expression evaluation across to the main event loop.
> server: isolate ptpython repl in its own event loop

- plugins/rknn/.gitignore
- plugins/rknn/.npmignore
- plugins/rknn/.vscode/launch.json
- plugins/rknn/.vscode/settings.json
- plugins/rknn/.vscode/tasks.json
- plugins/rknn/README.md
- plugins/rknn/package-lock.json
- plugins/rknn/package.json
- plugins/rknn/src/common
- plugins/rknn/src/detect
- plugins/rknn/src/main.py
- plugins/rknn/src/predict
- plugins/rknn/src/requirements.txt
- plugins/rknn/src/rknn/__init__.py
- plugins/rknn/src/rknn/optimized/yolo.py
- plugins/rknn/src/rknn/plugin.py
- plugins/rknn/tsconfig.json
This currently only works on the RK3588(S) chip, e.g. Orange Pi 5 and similar. Also assumes installation is Docker, running in privileged mode.
> rknn: initial rockchip object detector implementation

- install/config.yaml
Simple version bump for the HA Add On
> Home Assistant: Bump Add On to v0.99.0

- server/src/server-settings.ts
> Revert "server: make fetching network interfaces optional"

- install/local/install-scrypted-dependencies-linux.sh
- install/local/install-scrypted-dependencies-mac.sh
- install/local/install-scrypted-dependencies-win.ps1
Intended use case: https://github.com/bjia56/setup-scrypted
> installer: allow specifying exact server version to install

- plugins/rknn/package.json
- plugins/rknn/src/det_utils/db_postprocess.py
- plugins/rknn/src/det_utils/operators.py
- plugins/rknn/src/rec_utils/operators.py
- plugins/rknn/src/rec_utils/rec_postprocess.py
- plugins/rknn/src/requirements.txt
- plugins/rknn/src/rknn/plugin.py
- plugins/rknn/src/rknn/text_recognition.py
Includes preprocessing and postprocessing from https://github.com/airockchip/rknn_model_zoo/tree/main/examples/PPOCR
> rknn: add text recognition

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/main.ts
- packages/cli/src/service.ts
- packages/cli/tsconfig.json
Adding `tsconfig.json` `strict: true` to `packages/cli`
> Enable TypeScript strict for packages/cli

- server/python/plugin_remote.py
Allows getting a device by plugin name similar to JavaScript implementation.
> server: fix python systemManager.getDeviceByName

- server/bin/packaged-python.d.ts
- server/bin/packaged-python.js
- server/src/plugin/runtime/python-worker.ts
> server: allow plugins to customize python installs

- plugins/webrtc/src/ffmpeg-to-wrtc.ts
Cleaning up leftovers from #1558
> webrtc: remove missing var

- server/python/plugin_remote.py
Appears to work fine when listening to a dummy switch's BinarySensor
> server: implement python listen + listenDevice

- plugins/homekit/src/main.ts
Same changes of https://github.com/koush/scrypted/pull/1615 for Homekit
> Add flag to not autoenable devices on creation

- install/docker/docker-compose.yml
Fixed the comment to be consistent with the line below.
> Fix volume path comment

- plugins/doorbird/package-lock.json
- plugins/doorbird/package.json
This fixes a bug, where UDP broadcast packets sent by Doorbird would not be picked up when ran inside a docker container.
Fixes: #1703
> update underlying doorbird api package

- plugins/hikvision/src/hikvision-api-capabilities.ts
- plugins/hikvision/src/hikvision-api-channels.ts
- plugins/hikvision/src/hikvision-camera-api.ts
- plugins/hikvision/src/hikvision-overlay.ts
- plugins/hikvision/src/main.ts
Not sure about all these formatting changes, I just ran the format hotkey on webstorm :| will revert if it's a problem
> Hikvision: Ptz + presets implemented

- plugins/reolink/src/main.ts
Disable polling for siren, seems like it's broken for some user but I could not spot any reason so far
> Disable siren polling

- plugins/hikvision/src/hikvision-camera-api.ts
- Improved supplemental light handling to support turning on the supplemental white light for ColorVu models with IR.
- Doesn't add support for toggling the IR light.
- Tested on ColorVu cameras with and without IR (DS-2CD2387G2H-LISU/SL and DS-2CD2387G2-LSU/SL).
> hikvision: improve supplemental light mode handling
