koush/scrypted

- plugins/synology-ss/package-lock.json
- plugins/synology-ss/package.json
- plugins/synology-ss/src/main.ts
Eventually plan to automatically set up alerts in Surveillance Station using their API, but in the meantime this makes it possible by manually setting up alerts. Been testing it myself over the past week and works pretty well. Figuring out how three separate motion timeouts (Scrypted, Surveillance Station and on camera) interact is a bit hair-pulling though -- still unsure how best to coordinate them, or if it even matters.
> synology-ss: add motion detected webhook

- .github/workflows/docker.yml
This change causes the Github docker workflow to publish the image to both Dockerhub and [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).
Why? Dockerhub rate limits downloads unless you pay them and authenticate with Dockerhub.  This can be problematic for people with larger setups that don't want to pay up to Dockerhub, like myself.
I suspect this will "just work".  I don't recall having to setup any permissions magic on my repositories that I've done this with.  I believe you get a `secrets.GITHUB_TOKEN` secret for free that has scoped access to this repo.
> github action: publish to ghcr and dockerhub

- plugins/unifi-protect/src/main.ts
- Moved to libfdk_aac (because it's also used for homekit and has some nicer profiles that can be used)
- use High efficiency profile
- use as many threads as core are available
- avioflag and flush_packages flags to minimise latency
- max_delay to make sure the delay won't grow endlessly
- filter audio below 200hz en above 2500hz and use the afftdn filter to limit background noise and such 
- Limit bitrate to 16K , this seems to help agains crackling sound (maybe because it speeds up transcoding). Audio still seems very acceptable with 16K
> Attempt to enhance talkback quality

- plugins/amcrest/src/amcrest-api.ts
- plugins/amcrest/src/main.ts
There are two areas where Dahua doorbells (at least the model that I have tested, VTO2202F-P-S2) behave differently:
1. Event codes are used differently. More specifically, AmcrestEvent.TalkPulse should be ignored for Dahua doorbells. Also, other 3 new events were added.
2. Intercom also works slightly differently, we need to accumulate and send segments when they are over 1KB in size. 
I have added a setting for Dahua Doorbells to activate this different behaviour, however, I need your help figuring out how to better manage and present that setting. Right now if a user enables the Dahua Doorbell setting but disables the Amcrest Doorbell setting, it will disable the binary sensor which is obviously not what we want.
> Adding support for Dahua doorbells

- plugins/zwave/package.json
- plugins/zwave/src/CommandClasses/EntrySensorToBarrierOperator.ts
- plugins/zwave/src/CommandClasses/index.ts
- plugins/zwave/src/main.ts
- Added support to specify security keys according to here: [Security S2](https://zwave-js.github.io/node-zwave-js/#/getting-started/security-s2)
- Added support for Barrier Operator devices such as garage doors
Main issue is that the ZWave plugin will fail to load during the first run if you have the ZWave plugin installed as it will be attempting to convert the existing base64 storage value as hex. I was able to get my ZWave up and running after deleting the plugin, closing my browser, and then going through the setup again. Would be nice to have a way to convert an existing setup to a hex string value, but I'm not sure what the best way to do this would be. I suppose you can test if the existing value ends in "==" and go from there?
I've confirmed my garage door is added as a new …
> Add ZWave Security Keys and Barrier Operator Device Support

- plugins/google-device-access/src/main.ts
Allows the user to customize the endpoints used for authorization and
accessing the API in the google-device-access plugin by specifying
hostnames in storage. These can be configured using the
`authorizationHostname` and `apiHostname` keys, respectively.
> Support custom API endpoints in SDM plugin

- docker/install-scrypted-dependencies-mac.sh
This sets up scrypted to run under launchd as the currently logged in user. It will run at load, and keep alive in case it crashes.
It also will automatically detect the correct bin folder from brew, so it can run on Intel and Apple Silicon.
> Register as a service via launchd on macOS

- docker/install-scrypted-dependencies-mac.sh
This further improves the detection of npx on macOS, in case installs outside brew occurred, such as nvm or the official .pkg.
> Improve Reliability of npx

- plugins/myq/src/main.ts
Updated MyQ plugin to use device.family instead of device.type to recognize garage doors. This was intended to add support for gates, but it should allow any device that identifies as "garagedoor" to be recongnized.
> Use family instead of type. Works for gates.

- plugins/arlo/package-lock.json
- plugins/arlo/package.json
- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/camera.py
- plugins/arlo/src/arlo_plugin/provider.py
Changes:
- Return rtsp url immediately once we get it
- Extended plugin-level timeouts (used to clear up blocked stale coroutines) to 30s
- Restart auth if the headers don't work on plugin load
- Return arloq and doorbell device types as cameras
> arlo 0.2.3

- plugins/sendgrid/.gitignore
- plugins/sendgrid/.npmignore
- plugins/sendgrid/.vscode/launch.json
- plugins/sendgrid/.vscode/settings.json
- plugins/sendgrid/.vscode/tasks.json
- plugins/sendgrid/README.md
- plugins/sendgrid/package-lock.json
- plugins/sendgrid/package.json
- plugins/sendgrid/src/main.ts
Opening this PR to upstream the plugin, if you think it'd be useful enough to include in the main repo. 😃 
Getting started with SendGrid pretty much requires the user to own a domain name and be able to configure DNS records for domain authentication. Per SendGrid docs, it doesn't look like using public email domains like gmail, yahoo, etc. will actually deliver emails correctly.
> sendgrid: initial implementation

- plugins/zwave/src/CommandClasses/SettingsToConfiguration.ts
- Updating zwave-js to 9.2.1
- Support devices that have both "choices" and allow values to be filled in
> zwave: allow manual field entry

- plugins/homekit/src/types/sensor.ts
Door/open close sensor in ZWave is a ScryptedInterface.EntrySensor which was not supported by homekit
> homekit: map EntrySensor to homekit ContactSensor

- plugins/homekit/src/types/sensor.ts
Support IntrusionSensor in Homekit.
Context: https://github.com/koush/scrypted/blob/main/plugins/zwave/src/CommandClasses/index.ts#L88
The Z-Wave Home Security CC maps to IntrusionSensor.
> homekit: support IntrusionSensor as ContactSensor service

- plugins/homekit/src/types/sensor.ts
- plugins/homekit/src/types/thermostat.ts
bugfix: airquality sub-sensor displayed when it shouldn't be
support air quality sensor as part of thermostat type
> homekit: airquality sensor updates

- plugins/homekit/src/types/sensor.ts
Devices like Aeotec Door / Window Sensor 7 Pro support both BinarySensor and EntrySensor - but the EntrySensor attribute actually reflects the sensor state
> prefer EntrySensor over BinarySensor if device has both

- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/provider.py
The Arlo plugin attempts to discover the associated basestation(s) for the camera(s). Older basestations (like the VMB4000) advertise themselves as `siren` instead of `basestation`, so this PR allows these basestations to be discovered correctly. Tested working with Arlo Pro 2 cameras paired to VMB4000v3.
As a side note, I don't get any audio, but not sure if that's a plugin problem or a problem with how the basestation is advertising itself.
> feat: allow Arlo basestations that identify as sirens (e.g. VMB4000)

- plugins/homekit/src/types/common.ts
- plugins/homekit/src/types/thermostat.ts
Whilst working on a plugin for the Sensibo smart AC controller, I made a few changes to the HomeKit plugin to gracefully handle thermostats that don't have a fan or support an 'auto' mode. I also added a minimum step for the fan speed, which causes the Home app to 'stick' to valid fan speeds when adjusting the speed.
P.S. Hoping I've done this correctly,  but let me know if I need to change anything or if there's a procedure for PRs I should have followed.
> Some quality-of-life fixes for the HomeKit plugin

- plugins/alexa/package.json
- plugins/alexa/src/main.ts
- plugins/alexa/src/message.ts
- plugins/alexa/src/types/camera.ts
- plugins/alexa/src/types/common.ts
- plugins/alexa/src/types/doorbell.ts
- plugins/alexa/src/types/garagedoor.ts
- plugins/alexa/src/types/index.ts
I took a stab and updating the Alexa plugin, and start setting it up for expanded device support.  There was also a few things that could have been handled better around authentication and messageId that better aligned with the developer documentation that I implemented as well.  I have verified that existing support for `Camera` and `Doorbell` has continued to work.  In addition I have added support for `Garage`.
> added support for type `Garage` and refactored the controller for future support

- docker/install-scrypted-dependencies-win.ps1
Otherwise `OpenJS.NodeJS` defaults to v19 right now which is not supported https://github.com/koush/scrypted/pull/498
> Windows installation script install Node LTS v18

- docker/install-scrypted-dependencies-win.ps1
As discussed on Discord, it wasn't obvious if any libraries still required native compilation. https://discord.com/channels/882329362295316500/890705604849594388/1067562780036694156
If not, then we don't have to install the Node.js additional tools for Windows which is required to compile native modules, saving a lot of time in the installation process (since this installs a pandora's box of dependencies).
> Remove Node.js additional tools for Windows from Windows install script

- server/python/plugin-remote.py
The scrypted web ui looks to be reading from `cpu`: https://github.com/koush/scrypted/blob/64f696599c5bd09070e7716976f05404d635d6cf/plugins/core/ui/src/components/plugin/PluginStats.vue#L67 and is being published on the nodejs side as `cpu`: https://github.com/koush/scrypted/blob/227b287f1ee19f354a9174b8aef8bf475fe42efe/server/src/plugin/plugin-remote-worker.ts#L21
Might need to change this as well?
https://github.com/koush/scrypted/blob/cc43273f3417000ebe05fc22de75ae9faeddc07b/server/src/plugin/plugin-host.ts#L59
> Update python cpu reporting

- plugins/coreml/src/coreml/__init__.py
Tries to fetch the label list from the mlmodel file itself and due to newer converted mlmodels having a different output (float32) it also numpy converts the model output to floats.
> Accomodate custom models

- docker/install-scrypted-dependencies-win.ps1
Use forked version of `node-windows` addresses issue with `winsw.exe` compatibility in Windows 11 and Windows Sandbox
@koush please merge https://github.com/koush/node-windows/pull/1 and publish first
> Fix installing service in Windows 11 and Windows Sandbox

- plugins/ring/src/main.ts
I have no idea what is being done in homebridge, but this solution I came up with definitely works for me.
I did find that the `location.onLocationMode.subscribe` is explicitly **not** used if the location has a base station, which my location does. It's possible we might be over updating the location mode with this change for some users if they don't have a base station and also have a security panel, but it wasn't updating at all previously for my very simple ring setup. I'm also not sure what type of ring location doesn't have a base station but still can be armed, that part is a little confusing.
> fix ring alarm state when changing modes

- plugins/homekit/package.json
- plugins/homekit/src/types/garage.ts
- plugins/homekit/src/types/security.ts
- plugins/homekit/src/types/windowcovering.ts
- plugins/ring/package.json
- plugins/ring/src/main.ts
closes https://github.com/koush/scrypted/issues/482
This PR also fixes two unrelated warnings I noticed in the homekit logs for the garage and window covering type. The following was not needed as we already call `bindCharacteristic`
```
service.getCharacteristic(Characteristic.TargetDoorState)
.on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {
callback(null, targetState);
})
```
> ring: added night mode support to arm with sensor bypass

- plugins/eufy/src/main.ts
- plugins/eufy/src/stream.ts
Removed all of the stream caching and proxying code from livestreamer, all it's doing now is making the start stream and listen for events stuff a little easier to work with. Unfortunately, the api/client is very asynchronous and event driven, they don't expose a nice method like `await getStreamAndReturnIt`.
> eufy: motion, partial livestream removal & minor improvement in snapshots

- plugins/ring/package-lock.json
- plugins/ring/package.json
- plugins/ring/src/location.ts
- plugins/ring/src/main.ts
the fix for probing the devices on startup is in this pr too.
> ring: fix location mode subscriptions

- plugins/homekit/src/main.ts
- plugins/homekit/src/types/common.ts
- plugins/homekit/src/types/onoff-base.ts
- plugins/homekit/src/types/security.ts
- plugins/homekit/src/util.ts
This exposes the Scrypted OnOff interface to Homekit's SecuritySystem as a Switch. The Homekit UI will now show both the Arm/Disarm selector as well as the switch.
The intended use is for Arlo's basestation siren to emulate an arm/disarm to reduce the risk of being accidentally toggled.
> homekit: merge SecuritySystem & child Sirens as one Homekit accessory

- plugins/arlo/package-lock.json
- plugins/arlo/package.json
- plugins/arlo/src/arlo_plugin/arlo/arlo_async.py
- plugins/arlo/src/arlo_plugin/basestation.py
- plugins/arlo/src/arlo_plugin/camera.py
- plugins/arlo/src/arlo_plugin/provider.py
- plugins/arlo/src/arlo_plugin/siren.py
- plugins/arlo/src/arlo_plugin/spotlight.py
- plugins/arlo/src/arlo_plugin/vss.py
- plugins/arlo/src/requirements.txt
> arlo: camera [spot,flood]lights, sirens + only use interfaces when hardware supports it

- docker/fs/etc/avahi/avahi-daemon.conf
Enable ipv6 for avahi to allow multiple mdns server on one host
> Enable ipv6 for avahi

- .github/workflows/docker.yml
This should add mutable docker tags for the missing variants (full image without s6 and thin/lite images with s6) allowing for updating via simple docker pull
> Publish mutable docker tags for all variants

- plugins/chromecast/src/main.ts
- plugins/core/fs/examples/chromecast-view-camera.ts
Fixes #714 
Sometimes the cached `mediaPlayerPromise` is not the current media player, and sometimes `joinPlayer` returns a player that doesn't respond to `player.getStatus()`. I'm not sure about the root cause, but this PR seems to fix the issue where chromecast streaming cannot be stopped. 
Nest Hub Gen 2 is my only chromecast device, so I don't know if these changes have any side effects on other chromecast devices.
> chromecast: fix stop casting issue

- plugins/coreml/src/coreml/__init__.py
Hack to accomodate models that has an output of type Float32 instead of Double.
> coreml: accomodate MultiArray (Float32 0 × 80) models

- plugins/homekit/src/types/airpurifier.ts
- plugins/homekit/src/types/index.ts
- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
sdk and homekit support for AirPurifier type and associated FilterMaintenance interface
> add types to support Air Purifier

- common/src/ffmpeg-rebroadcast.ts
- plugins/prebuffer-mixin/src/main.ts
When an ffmpeg parser session is started, if ffmpeg exits before it is able to print out the sdp, the parse session will hang in `startPrebufferSession` while it waits for the sdp. This prevents the prebuffer restart loop from continuing forward and detecting that the session has already been killed.
The proposed solution is to reject the sdp promise if ffmpeg exits prematurely. The exception will propagate and allow the prebuffer restart loop to try again.
> rebroadcast: recover after ffmpeg exits before printing sdp

- plugins/snapshot/src/ffmpeg-image-filter.ts
Snapshots of raw images (e.g. via the snapshot url) frequently results in error when rescaling. A sample stacktrace:
```
[Snapshot Plugin]: -hide_banner -y -i pipe:[REDACTED] -filter_complex scale='min(512,iw)':-2 -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]: pipe:4: Invalid data found when processing input
[Snapshot Plugin]: ffmpeg exited
[Snapshot Plugin]: Snapshot failed Error: ffmpeg input to image conversion failed with exit code: 1, /usr/bin/ffmpeg -hide_banner -y -i pipe:4 -filter_complex scale='min(512,iw)':-2 -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]:     at /src/ffmpeg-image-filter.ts:177:23
[Snapshot Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
It looks like this might be a side effect due to switching from static ffmpeg to …
> snapshot: tell ffmpeg pipe input format

- install/docker/docker-compose.yml
- install/docker/fs/etc/s6-overlay/s6-rc.d/avahi/run
- install/docker/fs/etc/s6-overlay/s6-rc.d/dbus/run
- install/docker/fs/etc/s6-overlay/scripts/setup.sh
Trying to address https://github.com/koush/scrypted/issues/936.
Tested locally:
```
scrypted  | s6-rc: info: service s6rc-oneshot-runner: starting
scrypted  | s6-rc: info: service s6rc-oneshot-runner successfully started
scrypted  | s6-rc: info: service fix-attrs: starting
scrypted  | s6-rc: info: service setup: starting
scrypted  | SCRYPTED_DOCKER_AVAHI != true, won't manage dbus nor avahi-daemon
scrypted  | s6-rc: info: service setup successfully started
scrypted  | s6-rc: info: service dbus: starting
scrypted  | s6-rc: info: service dbus successfully started
scrypted  | SCRYPTED_DOCKER_AVAHI != true, not starting dbus-daemon
scrypted  | s6-rc: info: service avahi: starting
scrypted  | s6-rc: info: service fix-attrs successfully started
scrypted  | s6-rc: info: service legacy-cont-init: …
```
> improve management of avahi

- plugins/python-codecs/src/main.py
Union type annotations with `|` were introduced in python 3.10: https://peps.python.org/pep-0604/
This change makes the annotations compatible with 3.9.
Fixes #995.
> python-codecs: make annotations compatible to pre-3.10

- plugins/core/src/aggregate.ts
The current video filter to scale source videos for aggregate streaming only handles vertical (width) padding. If the source video instead has a height that's too small for the target aspect ratio (e.g. some Arlo cameras have 1920x1072 instead of 1920x1080), the video filter fails with:
```
[RTC Connection Bridge]: [Parsed_pad_2 @ 0x56539a2a2f40] Padded dimensions cannot be smaller than input dimensions.
[RTC Connection Bridge]: [Parsed_pad_2 @ 0x56539a2a2f40] Failed to configure input pad on Parsed_pad_2
[RTC Connection Bridge]: Error reinitializing filters!
[RTC Connection Bridge]: Failed to inject frame into filter network: Invalid argument
[RTC Connection Bridge]: Error while processing the decoded data for stream #3:0
[RTC Connection Bridge]: Conversion failed!
```
The proposed …
> core: add horizontal padding to aggregate streams

- plugins/core/ui/src/interfaces/sensors/PositionSensor.vue
The default Leafletjs marker icon has preconfigured values for where to place the image in relation to the pixel coordinate that matches its anchor. This default was previously ignored since the icons were missing, but the alternative did not have the correct anchor coordinates. This change restores the default marker behavior.
Also disables touch-zoom to behave more like a static image.
> core: use webpack bundled map marker

- plugins/unifi-protect/src/camera.ts
When utilizing stacked NVRs with the `unifi-protect` plugin, we encountered an issue where the plugin failed to generate correct RTSP stream URLs for cameras connected to the secondary NVR. This limitation stemmed from the fact that only the primary IP was available and configurable in the UI. As a result, we could only access camera streams from the primary NVR, rendering those on the secondary NVR inaccessible.
To address this issue, we revised the approach to generating RTSP stream URLs. Instead of statically utilizing the primary NVR's IP, we integrated the use of the connectionHost property, which is returned from the API for each camera. The `connectionHost` property contains the specific IP address of the host NVR that a camera is connected to, ensuring that the correct IP address …
> unifi-protect: Use connectionHost to support cameras distributed between stacked nvrs

- plugins/core/ui/src/components/builtin/ShellComponent.vue
- server/src/runtime.ts
Whenever I use the shell terminal for anything nontrivial, it frequently misbehaves by wrapping output in odd ways. This PR is a coordinated change between server and core by updating the engine.io/shell endpoint's interface to send annotated packets - aside from data messages, a `dim` packet can be sent to change the pty dimensions on the server side.
We can see all the screen real estate being used here:
> server & core: send terminal size info

- plugins/core/ui/src/components/builtin/ShellComponent.vue
- server/src/runtime.ts
Follow up to #1148 
Binary data now treated properly as such. Also optimizes the common data transfer cases by reducing the bytes sent in the stringified message and removing stringification entirely for server-sent data.
> server & core: handle binary terminal data

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
This is a follow up to #1020.
I've added device detection so the `autotrack` stream is only added if it is a TrackMix device and kept the cleanup of loops and arrays etc. There's a lot more we could implement using the device information, could automatically configure a doorbell, set known-good configuration for each model etc. but this is a good place to start.
Unfortunately the way we are interacting with the API seems to not be supported by all devices - my doorbell doesn't seem to like the encoding & info GET requests. Based on the semi-official/supported [python API ](https://github.com/ReolinkCameraAPI/reolinkapipy) we should be generating a token after login to be used in a `POST` request. I've tested this library and seems to work well across all my cameras & doorbell, so maybe a …
> reolink: Added device detection + trackmix stream

- packages/client/src/index.ts
- server/python/plugin_remote.py
- server/src/plugin/connect-rpc-object.ts
- server/src/plugin/plugin-remote-worker.ts
- server/src/runtime.ts
Also changes the checksums computed on the python side to be symmetric to node's signatures (both now use base64 encoding).
> server, client: send full ClusterObject on new eio endpoint

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/main.ts
- packages/cli/src/shell.ts
- plugins/core/src/terminal-service.ts
- plugins/core/ui/src/components/builtin/ShellComponent.vue
This is a reimplementation of #1153, but following the new design paradigm of using connectRPCObject and buffering data.
~~Unfortunately, I'm not able to get non-interactive shell working for the current setup - testing `echo date | node ./dist/packages/cli/src/main.js shell localhost:10443` closes the connection immediately without any output. Probably needs a change to core plugin to keep the connection half-open if one generator ends before the other, but that's a bit tricky to do since it's unclear when to terminate the child process. In my opinion, that part can wait for later as an enhancement, since interactive shell is going to be the main use case.~~
^ noninteractive use has been implemented in 30db66d2d353dce6b0817bd94c1c5575b5cd090a
> cli, core, ui: add `npx scrypted shell` and support interactive/noninteractive shells

- packages/cli/src/main.ts
- packages/cli/src/shell.ts
- plugins/core/src/terminal-service.ts
Allow `npx scrypted shell` to send a remote command and arguments to the TerminalService, instead of just running the shell. Also preserves the buffer format for noninteractive use since the string conversion breaks binary communication over the channel.
Tested with the following, which provides an ssh tunnel over this connection:
`socat -d -d -d tcp-listen:50505,fork,reuseaddr,nodelay exec:"node ./dist/packages/cli/src/main.js shell localhost\:10443 -- socat - tcp\:localhost\:22"`
> cli, core: support invoking remote commands

- plugins/cloud/README.md
The original wording implies that `sudo cloudflared service install` is part of the token which is incorrect.
> docs: Improve clarity of Cloudflare token copying instructions

- plugins/core/package-lock.json
- plugins/core/ui/src/components/Drawer.vue
- plugins/core/ui/src/components/builtin/SettingsComponent.vue
- plugins/core/ui/src/components/plugin/plugin.ts
Replaces use of corsproxy with pulling latest docker tag info from scrypted server
> core: query latest docker image via scrypted server

- plugins/onvif/src/onvif-api.ts
Some ONVIF events from Axis cameras seem to come in as arrays with multiple events. They don't appear related to motion, so ignoring them resolves a crash
https://discord.com/channels/882329362295316500/1193557841051664425/1193896551974707340
> ONVIF: ignore invalid (array) ONVIF events from Axis cameras

- npm-install.sh
Since a lot of plugins now depend on the `auth-fetch` package, the `npm-install.sh` script should probably set it up so it works out of the box.
Otherwise users will get an error when trying to debug plugins for the first time
```
> @scrypted/snapshot@0.2.34 prescrypted-vscode-launch
> scrypted-webpack
[
{
moduleIdentifier: 'C:\\Users\\Long\\Desktop\\scrypted\\sdk\\node_modules\\ts-loader\\index.js!C:\\Users\\Long\\Desktop\\scrypted\\packages\\auth-fetch\\src\\auth-fetch.ts',
moduleName: '../../packages/auth-fetch/src/auth-fetch.ts',
loc: '79:68-93',
message: "Module not found: Error: Can't resolve 'http-auth-utils' in 'C:\\Users\\Long\\Desktop\\scrypted\\packages\\auth-fetch\\src'",
moduleId: '../../packages/auth-fetch/src/auth-fetch.ts',
moduleTrace: [ [Object], [Object] ],
details: …
```
> npm-install.sh install auth-fetch package

- npm-install.sh
Not sure if there was a prior reason for not including a shebang, but I found that the script doesn't work under the fish shell due to the absence of pushd/popd
> add bash shebang

- plugins/homekit/src/types/camera/camera-snapshot.ts
- plugins/snapshot/src/main.ts
- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
I noticed after the snapshot timeout was added in https://github.com/koush/scrypted/commit/0e700a53d0a673e336cdaca7e0265ed3bd30ae2e, my Homekit snapshots were always delayed (the update would show the previous update maybe 70% of the time).
After doing some debugging, I noticed that my specific set up (Dahua/Amcrest 6MP cameras) would always take around a fraction of a second longer (e.g. 1.4 seconds) to return the snapshots. (I've always tried adjusting the snapshot quality but it didn't make a big enough difference). I assume this is just the nature of 6MP snapshots.
I believe the 1 second timeout was added to minimize any delays it may cause HomeKit which is understandable, however I'm willing to sacrifice a marginal delay for more up-to-date snapshots, especially over mobile where the …
> Periodic snapshot timeout

- plugins/snapshot/src/main.ts
My PR https://github.com/koush/scrypted/pull/1295 had a bug where I was using `this.debugConsole` but it was `undefined` if debug logging wasn't available.
> snapshot: Fix debugConsole error

- sdk/types/package-lock.json
- sdk/types/package.json
- sdk/types/tsconfig.json
Slowly adding `tsconfig` `strict` mode to all projects.
`sdk/types` was pretty easy, everything was compatible with strict.
I removed `@types/rimraf` since it didn't seem like it's being used besides the `package.json` `build` CLI command so is not necessary. Added `@types/node` which is necessary.
Fixed `include` path to actually point to `src`.
> Add tsconfig strict to `sdk/types`

- plugins/alexa/.vscode/settings.json
- plugins/alexa/package-lock.json
- plugins/alexa/package.json
- plugins/alexa/src/alexa.ts
- plugins/alexa/src/main.ts
- plugins/alexa/src/types/fan.ts
- plugins/alexa/src/types/index.ts
- plugins/alexa/src/types/light.ts
- plugins/alexa/src/types/light/handlers.ts
- plugins/alexa/src/types/outlet.ts
Added support to the `alexa` plugin to support `Light`, `Outlet`, and `Fan` device types along with `ColorSettingsHsv` and `ColorSettingTemperature` beyond the standard interfaces.
> alexa: added support for `light`, `outlet`, and `fan` device types

- sdk/types/src/build.ts
- sdk/types/src/tsconfig.json
- sdk/types/tsconfig.typedoc.json
@koush I noticed you [added support for required properties](https://github.com/koush/scrypted/commit/bee77e121eafaa983b42e5c3634d74f5e3b8d43e) in the `build.ts` but I realised we can actually do this dynamically from the typedoc schema. 
In the future we can improve the types even further for `function toTypescriptType(type: any): string` and `function toPythonType(type: any): string {` but it was too much trouble so ignoring for now.
> SDK types build: calculate required/optional fields from schema

- plugins/mqtt/package-lock.json
- plugins/mqtt/package.json
- plugins/mqtt/src/autodiscovery.ts
- plugins/mqtt/src/color-util.ts
- plugins/mqtt/tsconfig.json
I have added support for colored lights in the current MQTT design. In my testing this works with both Z2M and ZHA in Home Assistant.
> mqtt: add support for `ColorSettingTemperature` and `ColorSettingHsv`

- .github/workflows/build-sdk.yml
- plugins/snapshot/src/main.ts
- sdk/src/index.ts
- sdk/src/storage-settings.ts
- sdk/tsconfig.json
- sdk/types/package-lock.json
- sdk/types/package.json
- sdk/types/src/build.ts
- sdk/types/src/tsconfig.json
- sdk/types/src/types.input.ts
- sdk/types/tsconfig.json
Enable TypeScript strict for `sdk/types`
Enable TypeScript strict strict for `sdk`
Fix various type-related issues
Add `build-sdk` GitHub Actions workflow to ensure SDK builds and doesn't have errors
> Add strict types to sdk

- common/src/autoenable-mixin-provider.ts
- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
Discovered while I'm fixing the strict types for snapshot plugin
I presume because the description specifically mentions "Returns null if a mixin can not be created" and the [usage of `canMixin` checks for null](https://github.com/koush/scrypted/blob/e5d60cf3e00e4bf399a75563aab9b85192af5224/common/src/autoenable-mixin-provider.ts#L51), that `null` is the correct response type here.
> Fix type of canMixin

- common/src/rtc-signaling.ts
On Firefox, it appears that calling `createLocalDescription` multiple times, which triggers multiple `createOffer` calls, will reset the PeerConnection state in such a way that the returned SDP no longer includes any gathered candidates.
In SIP.js, their approach is to initialize a PeerConnection, call `createOffer` once, then when either ICE gathering finishes or a timeout expires, use the `localDescription` property to generate an SDP - their chain of events can be found [here](https://github.com/onsip/SIP.js/blob/2e1c525279c8d6deebb6ecaf3d14477ab7b63310/src/platform/web/session-description-handler/session-description-handler.ts#L272).
This change will allow a Scrypted peer to emulate such behavior by:
- Calling `createLocalDescription` without `sendIceCandidate`, in cases where the …
> common: fix behavior of multiple createLocalDescription calls on firefox

- plugins/amcrest/README.md
- plugins/amcrest/src/amcrest-api.ts
- plugins/amcrest/src/main.ts
I have a Dahua VTO video intercom that works great with the Amcrest plugin, but also has a built in access control door lock/unlock mechanism that I'd like to use in automation inside of scrypted. This adds support for locking/unlocking when explicitly enabled for Dahua Doorbells.
I have tested this in my system locally and believe it will work with most standard VTO configurations, but happy to submit a video or similar if needed to get this merged.
Thanks!
> amcrest: Add support for Dahua VTO built-in access control lock as a `Lock`

- plugins/homekit/src/types/common.ts
Merged devices today are always synced into homekit, whether enabled or not. This adds a check to ensure that the child device was requested to be synced before merging.
cc @zeliardm
> homekit: merge child device only if child has homekit enabled

- server/package.json
Should fix:
- Python Codecs installation error due to PyGObject compilation failure on Linux
- `debugpy` crashes on python 3.11
> server: bump python runtime

- server/python/plugin_remote.py
Repro in a Python REPL:
```python
d = systemManager.getDeviceByName("MyCamera")
await d.getVideoStreamOptions()
await d.getVideoStreamOptions()
```
Gives error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/brettjia/workspace/scrypted/server/python/plugin_remote.py", line 87, in apply
device = await self.device
RuntimeError: cannot reuse already awaited coroutine
```
> server: treat self.device as future

- plugins/rknn/README.md
- plugins/rknn/package-lock.json
- plugins/rknn/package.json
Based on what was discussed in https://github.com/blakeblackshear/frigate-hass-addons/issues/145
> rknn: update docs to remove dependence on full privileged docker

- plugins/rknn/package-lock.json
- plugins/rknn/package.json
- plugins/rknn/src/rknn/plugin.py
The additional CPUs are supported by Rockchip's model converter tool, but unknown if they will actually properly run Scrypted and the rknn plugin. These models have been converted and uploaded here: https://github.com/bjia56/scrypted-rknn/tree/main/models
> rknn: add more cpus

- install/local/install-scrypted-dependencies-win.ps1
- packages/cli/src/service.ts
- server/src/plugin/plugin-npm-dependencies.ts
Fixes https://github.com/koush/scrypted/issues/1453 incompatibility with Node 20.12.2 on Windows. https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2
I looked for all usages of `child_process.spawn` which invoked a `.cmd` file and added `shell: true` (conditionally since I didn't want to change non-Windows behavior)
I also wrapped the `NPX_PATH_ESCAPED` because the path will contain spaces e.g. `C:\\Program Files\\nodejs\\npx.cmd` which doesn't work with `shell: true`
There were other usages of `child_process.spawn` which were for `ffmpeg` and `ffplay` which I don't think needs any change since those are `.exe` files.
> Fix Node 20.12.2 child_process.spawn .cmd EINVAL on Windows

- plugins/tapo/package.json
- plugins/tapo/src/main.ts
- plugins/tapo/src/tapo-api.ts
The tapo stream just needed another `\r\n` to accept the requests. Working great for me via the UI and HomeKit (after reload).
> Fix Tapo 2-way audio

- plugins/webrtc/src/wrtc-to-rtsp.ts
The audio transceiver sender can set its codec after the initial setup, but a null value was being stored if it wasn't immediately available. This PR simply checks the codec whenever the intercom starts rather than using the cached value. 
This (along with #1461) totally fixes my ring pro doorbell two-way audio. It makes sense because when I would force the ring plugin to use the "browser" webrtc endpoint, it immediately turned on 2-way and set up the codec, making the cached value correct. But the web socket ring webrtc endpoint delays 2-way setup, so the initial audio codec is null, and `wrtc-to-rtsp` would error when starting the intercom even though the codec was set up correctly at that point.
> webrtc: don't store audio codec before intercom start

- plugins/homekit/src/types/camera/camera-streaming.ts
When my ring doorbell sets up a streaming session, the first message on the audio return channel isn't a request to setup 2way. In that case, the "once" handler would fire (and bail) and when the real 2way setup message would arrive, the setup listener was no longer registered and nothing would happen. This PR moves the 2way setup into the always-on listener, and creates a guard to prevent multiple setup requests from running concurrently. It should also allow retrying the setup if something temporarily went wrong on a previous attempt.
> homekit: fix late 2way setup

- server/src/server-settings.ts
This allows Scrypted server to start up in UserLAnd on Android without rooting.
> server: make fetching network interfaces optional

- packages/cli/src/service.ts
Addresses issue with installing on Windows when the user profile directory contains a path, e.g. `C:\Users\john doe` https://discord.com/channels/882329362295316500/1237486685030322176/1238683790562431066
The `child_process.spawn` with `shell: true` ([required for Node 20.12.2 on Windows](https://github.com/koush/scrypted/pull/1455)) would fail if there are spaces in the path
> Fix Windows server install with installDir containing space

- server/src/scrypted-main-exports.ts
Follow up to #1477 
Sample usage for Android:
`patch.js`
```js
const os = require('os');
os.networkInterfaces = () => JSON.parse(process.env.SCRYPTED_INTERFACES);
```
launch scrypted server as:
```
SCRYPTED_COMPATIBILITY_FILE=/root/patch.js SCRYPTED_INTERFACES='{"eth0":[{"address": "192.168.0.188","family": "IPv4"}]}' npm run serve
```
> server: add SCRYPTED_COMPATIBILITY_FILE

- server/python/plugin_remote.py
Mainly useful to identify if someone is using portable-python or system python.
> server: print python interpreter path

- plugins/homekit/src/types/camera.ts
- plugins/homekit/src/types/camera/camera-recording.ts
Fix `r?.throw` because the generator is already closed/finished by the time it runs, so it never triggers the `catch()`
Added `console.log` to print a more friendly error message (only include error code is if it's >0)
Moved `!isOpen()` check. HAP requests last fragment even though it's already closed the recording stream. Now the fragment request is ignored entirely (rather than just skipping the `yield`).
> Homekit camera close recording tweaks

- install/docker/docker-compose.yml
- install/docker/install-scrypted-docker-compose.sh
While running the Avahi daemon on the host and scrypted in a docker container, I noticed that the homekit plugin would fail with the following exception:
Debugging the homebridge lib, I found out that it was caused by this error:
```
'An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)'
```
I found this snippet in the homebridge docs (https://github.com/homebridge/homebridge/wiki/mDNS-Options#avahi-linux-and-docker)
> Unless you've disabled AppArmor on your Linux distro, or it's disabled by default, you'll also need to set a security_opt setting of apparmor:unconfined, otherwise …
> Add security_opt to allow the container to talk to host avahi daemon

- .github/workflows/test.yml
This should let the test properly target the install scripts and the scrypted server version contained within the commit SHA that triggered the test.
Tests run on MacOS 13 and 14 to capture both x64 and arm64, respectively.
> actions: replace local install test with setup-scrypted action

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
I purchased some CX410's the other day and noticed that the Video Analysis plugin wouldn't recognize the cameras as it does my POE Doorbell.
With this patch, I can create a new smart motion sensor for the camera, and the object detector drop down will show 'dog_cat', 'people', and 'vehicle' as expected.
> reolink: save GetAiState to hasObjectDetector so object detector can work

- plugins/reolink/package-lock.json
- plugins/reolink/package.json
- plugins/reolink/src/main.ts
A few changes here:
1. the doorbell checkbox is removed from the UI.  We can auto-detect it using the `type` field from `GetDevInfo`.
2. ~`hasObjectDetector` is changed to a boolean and inferred by a call to `GetAiState` when the camera is created~
3. a new ONVIF dropdown in the UI - the user can choose whether to use ONVIF detection or polling the camera's `GetAiState`
4. ONVIF events are mapped to the values that come back from GetAiState, which are in turn picked up by the video analysis plugin
5. Bump the plugin version
Thanks!
> reolink: add ONVIF objection detection for cameras that can support it

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
This changes the camera to be a DeviceProvider, so that a Siren device can be provided by the camera if siren mode is supported.  Siren support is inferred via the GetAbility API.
For my PoE doorbell, I noticed that the alarm_mode = "manul" won't trigger the siren.  Using the siren's timed mode instead and pumping the API is a workaround.
> reolink: add siren support

- plugins/reolink/src/main.ts
Looks like I inadvertently caused a bug.  It's more than likely I had a cached response in my storage settings from intermediate code.
Anyway, my "production" instance of Scrypted synced up with the latest publish and I couldn't see the sirens after adding in my test camera.
This fixes it.
Apologies as I'm still learning my way around this codebase.
> reolink: fix deviceprovider for cameras with siren

- plugins/homekit/src/types/windowcovering.ts
Updates window covering homekit plugin to allow devices to control the target position through the entryOpen and brightness attributes.
> fix window covering target position binding

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
I noticed that I was unable to login to some of my cameras with Scrypted because my passwords have hyphens and spaces in them.  In fact, the latest firmware available for my RLN36 NVR and CX410s requires the passwords to have passwords with mixed alpha-numeric and various symbols as can be seen from this screenshot:
Here we'll switch over to using the Login API which has a JSON payload for the password.  Each of the functions will check if the token has expired, and if so, we will re-perform the login to get a new token.
> reolink: use Login json api to get around URL escaping limitations with some firmware

- server/src/plugin/plugin-npm-dependencies.ts
Fixes https://discord.com/channels/882329362295316500/932852072024518726/1256029193842593913
Similar to https://github.com/koush/scrypted/pull/1471 but fixes plugin install calling `npm --prefix ... install` (which I wasn't aware of before) in a Windows path containing space which had an error
I reproed the issue and here was the log which led me to the issue
```
plugin start/fork failed Error: npm installation failed with exit code 1
at installOptionalDependencies (C:\Users\john doe\.scrypted\node_modules\@scrypted\server\dist\plugin\plugin-npm-dependencies.js:78:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.onLoadZip (C:\Users\john doe\.scrypted\node_modules\@scrypted\server\dist\plugin\plugin-remote-worker.js:266:13)
at async …
```
> Fix plugin NPM dependencies failing to install on Windows with path containing space

- server/python/plugin_remote.py
In the Python implementation, sourcePort is always present in the cluster object, but can be None. When the key is present, this value is always part of the Python hash calculation. On the JavaScript side, even when the key is present and set to null/undefined, it's excluded from the hash calculation. This change makes the Python calculation consistent with the JavaScript implementation.
> server: fix python connectRPCObject sha256

- plugins/prebuffer-mixin/src/main.ts
- plugins/prebuffer-mixin/src/stream-settings.ts
- sdk/types/src/types.input.ts
Adds a new stream source type `synthetic` which represents a stream source generated by software running on the Scrypted server. This is treated the same as cloud cameras, where it's not prebuffered by default unless manually enabled.
> sdk, rebroadcast: don't automatically prebuffer synthetic streams

- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
Intended to be used by btop plugin to add the path where btop is installed to the interactive terminal.
> sdk: add TTYSettings

- server/python/plugin_remote.py
So... I'm not sure how this ever worked.
The unzipped path wasn't added to the Python system path, so it was never explicitly available when looking up modules. It seems that pure-Python sources were unaffected, however loading binary extension modules bundled together inside the plugin (e.g. plugins compiled by [Nuitka ](https://github.com/Nuitka/Nuitka)) would never get found. This change adds the unzipped path but keeps existing behavior
This change will need some additional beta testing before release. I am able to load existing plugins just fine (OpenCV, Python Codecs, OpenVINO, btop, btop-camera).
> server: add unzipped path to python module lookup path

- plugins/webrtc/package-lock.json
- plugins/webrtc/package.json
- plugins/webrtc/src/ffmpeg-to-wrtc.ts
- plugins/webrtc/src/main.ts
I was able to test this by converting a WebRTC mixin device (since that implements RTCSignalingChannel) to FFmpegInput, then ffprobe-ing the returned RTSP.
> webrtc: convert RTCSignalingChannel to FFmpegInput + consolidate all converters

- server/src/scrypted-server-main.ts
Used for accepting other mime types such as `application/sdp`
> server: allow all application/* mime types

- server/package-lock.json
- server/package.json
- server/src/plugin/runtime/python-worker.ts
Usage: 
Also adds a check to kick the install if the build tag doesn't match, since the exe path will be the same if the Python version doesn't change.
> server: allow plugins to specify portable python build tags

- server/python/plugin_remote.py
Enables connectScryptedClient in the browser to access the API on behalf of Python plugins
> server: python createMediaManager func

- plugins/objectdetector/src/main.ts
From my testing, this duration is long enough for a mixin on the Notifier to fetch the original image when NVR sends the push notification.
I am not sure what the implications of keeping these frames for 5x the original duration would be, especially on memory. If this is a problem, an alternate solution may be for the mixin plugin to listen for ObjectDetector events and request/cache detection input frames immediately, then use its local cache when notifying. This would require some server work to implement listen() for Python plugins.
> objectdetector: extend retention of detection inputs to 10s

- plugins/core/src/converters.ts
Stopgap fix for excessive memory usage when something repeatedly converts to a LocalUrl media type
> core: clear local url converter cache after 10m

- server/src/plugin/runtime/child-process-worker.ts
- server/src/plugin/runtime/python-worker.ts
In the case where a plugin requests a non-standard Python version that must be installed via portable-python, the extra pipes are used via PassThroughs and errors are not properly caught. This results in a high probability of a server crash when the plugin is killed and restarted.
> server: aggressively catch child process pipe errors

- plugins/alexa/package-lock.json
- plugins/alexa/package.json
- plugins/alexa/src/main.ts
Not sure if this is only an issue for me, but it's very annoying to have devices autmatically pushed to alexa before any changes could be done on the devices
Please any hint would be appreciated if this is not the right way to make this thing configurable
> Add to alexa an option to not auto-enable devices

- plugins/core/src/automation-actions.ts
- plugins/diagnostics/src/main.ts
- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
This change spins off from conversation at https://github.com/scryptedapp/homeassistant/pull/1 and allows consumers of the `Notifier` interface to specify a channel for notifications to be sent to. Android platforms can use this to send notifications to a specific channel, allowing the user to have fine-grained control over the audio and priority of the notifications they receive.
I'm not certain my `automation-actions.ts` edit is enough to make this work, I didn't readily see where these were consumed in the codebase.
Potential TODOs:
- Consumers of Notifier that might want to set a channel:
* `manage.scrypted.app` - Should the frontend test notification set a channel of `testing` or should it stay with the general channel? https://github.com/koush/manage.scrypted.app/blob/168317f6790e701 …
> feat(sdk): add support for notification channel in NotifierOptions

- install/local/install-scrypted-dependencies-win.ps1
I was just testing the Windows install script recently and noticed that it would actually fail on the `npx` commands
After some digging it's due to Node.js removing creating the `%APPDATA%\npm` folder in the MSI installer https://github.com/nodejs/node/commit/0ae8bf8dbc3d5db9a604c7be66aa22893e109fa0 which then causes the `npx` command to fail https://github.com/nodejs/node/issues/53538
This was fixed in `npm` https://github.com/npm/cli/pull/7640 but it's not included with the npm installed in Node 20.11.1 specified in the install script
This `npm i -g npm` is a workaround https://github.com/nodejs/node/issues/53538#issuecomment-2223853437
Also added `#Requires -RunAsAdministrator` so the script will error if it's not run under admin
> Update Windows install script workaround npm issue

- install/local/install-scrypted-dependencies-win.ps1
Testing the Windows install script again, the latest version of `npm` is no longer compatible with Node version `20.11.1` which is what's installed by Chocolatey. 
It spits out an error when running `npm i -g npm`
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@11.0.0
npm ERR! notsup Not compatible with your version of node/npm: npm@11.0.0
npm ERR! notsup Required: {"node":"^20.17.0 || >=22.9.0"}
npm ERR! notsup Actual:   {"npm":"10.2.4","node":"v20.11.1"}
```
because the NPM engine requires at least 20.17.0 https://github.com/npm/cli/blob/f7da341322c2f860156e8144b208583596504479/package.json#L258
Update the Windows install script Node version to `20.18.0` which is the latest Node LTS and is also supported …
> Fix Windows install script NPM/Node version clash

- server/package-lock.json
- server/package.json
- server/python/plugin_remote.py
Follow up to #1668 
Also bumps portable-python to version with Python 3.13 distributions
> server: use `standard-telnetlib` for Python 3.13+

- server/src/plugin/runtime/python-worker.ts
We had a Synology Docker user who upgraded to server 0.126.0 however Python plugins which specifically asked for Python 3.10 failed to load with ENOENT when looking for `/usr/bin/python3.10`. It turns out that `SCRYPTED_PYTHON310_PATH` was still defined (unknown if Synology transferred the env from the previous container) and prevented these plugins from starting. This adds a check to verify that the path pointed to by the env var exists before committing to selecting it as the runtime.
> server: check if `SCRYPTED_PYTHON*_PATH` env points to valid path

- common/src/ffmpeg-hardware-acceleration.ts
While familiarizing myself with the architecture of this project I noticed that this block is unreachable and handled above. Figured I'd submit a quick fix.
Awesome project BTW.
> Removed unreachable block

- .github/workflows/test.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> actions: add Linux arm64 runner to tests

- plugins/hikvision/src/hikvision-camera-api.ts
I have an ERI-K104-P4 NVR - which is only a couple of years old, but doesn't support these channel capability checks.  This lets Scrypted fallback to H264/AAC similar to the DS-76098NI-E2.
Works great now with a 4 channel set up.
> hikvision: add ERI-K104-P4 to the list of NVRs that doesn't support channel cap checks

- plugins/homekit/src/types/common.ts
- plugins/homekit/src/types/thermostat.ts
I am using Scrypted to pull my thermostat settings into Home Assistant via the HomeKit Controller and noticed that they require the following characteristics to be set to show the `Fan Mode` and `Humidity` settings on their climate card.  
* `Characteristic.TargetFanState` as [seen here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit_controller/climate.py#L161) to enable Fan Modes.  
* `Characteristic.CurrentFanState` as [seen here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit_controller/climate.py#L674) to indicate if the fan is active
* `Characteristic.TargetRelativeHumidity` as [seen here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit_controller/climate.py#L633) to enable Humidity …
> homekit: Added Common Humidifer/Dehumidifer Settings to Thermostat and Fans

- server/python/cluster_setup.py
Omit None fields from the hash calculation
> python: fix hash calculation

- plugins/core/src/main.ts
- plugins/core/src/terminal-service.ts
Enable `terminalservice` to fork across cluster nodes. This allows TTY plugins to tell `terminalservice` which node to launch its PTY.
> core: terminalservice fork across cluster

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
Improves handling of online state on Reolink battery camses, increasing the checking on the online state and allow the snapshot plugin to get more relevant snapshots
Fix for battery camera motion reporting, it comes as an event instead of Ai result
> Battery cams api fixes

- plugins/core/src/terminal-service.ts
When navigating away from a TTY page, it appears that the async generator exits without raising any exceptions. This can cause core to keep the subprocess (and RPC objects) active even when the xtermjs window no longer exists. The fix is to always clean up the subprocess.
> core: exit terminal's subprocess on generator end

- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
I skipped all the changes to versions of package.json, I did it only in the py file
not sure if I missed anything
Used this as reference https://github.com/koush/scrypted/commit/5d87a1b2dd6b1d40a531a255df81985eed40be39
> Sensors interface

- plugins/reolink/src/main.ts
- plugins/reolink/src/reolink-api.ts
- Adds polling to discovered devices, to check current state. Avoid the call if camera is sleeping, since all these commands are meant to actually wake up battery cams
- Remove on property initialization of devices to false, this would actually triggers everytime reset of the actual devices on plugin restart 
There could be a different call for older cameras on the Siren device, I could not test it out. Would go for the V2 now and check if any issue will be reported on older devices. There should be just a property version to check
> Add polling to reolink discovered devices

- plugins/snapshot/src/main.ts
Current implementation of snapshots for sleeping cameras would discard the latest acquired if requested with an event, this PR would try to let the snapshots for these longer and to not discard in case of events requests
> Allow sleeping cameras to have longer lived snapshots

- server/python/plugin_remote.py
- server/python/plugin_repl.py
This new Python REPL no longer requires telnet, many threads, and several buffer bounces: typing should be more responsive. This change uses the shared cluster_listen_zero function and bridges its streams into the REPL object directly. Multiple concurrent REPLs works as previously, and still requires invasive monkeypatching of ptpython/prompt_toolkit.
> python: partial repl reimplementation

- plugins/webrtc/package.json
- plugins/webrtc/src/ffmpeg-to-wrtc.ts
When trying to connect from Home Assistant (camera card) from a Realme tablet , the following log comes to the WebRTC plugin:
```
linux x64 #202311151304 SMP PREEMPT_DYNAMIC Thu Nov 16 08:20:12 UTC 2023
server version: 0.137.0
plugin version: @scrypted/webrtc 0.2.77
full
########################
4/26/2025, 9:59:18 AM
########################
................
[Домофон] Client Stream Profile {
transcodeBaseline: true,
sessionSupportsH264High: true,
maximumCompatibilityMode: false,
userAgent: 'Mozilla/5.0 (Linux; Android 11; RMP2106 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/135.0.7049.111 Safari/537.36 Home Assistant/2025.4.3-15918 (Android 11; RMP2106)',
capabilities: {
audio: { codecs: [Array], headerExtensions: [Array] },
video: { codecs: …
```
> Fixed an issue for some devices. They send screen width as not even value

- server/python/plugin_pip.py
Had an issue running Scrypted in Windows under a PT-BR install. The default user on this case is created as "Usuário" and pip was complaining about not finding the home dir. 
With this fix I'm able to run it in Windows.
> Fallback pip to latin

- sdk/types/scrypted_python/scrypted_sdk/types.py
- sdk/types/src/types.input.ts
- Add a property sourceId to ObjectsDetected to help identify from where the object detections come from on consumer plugins
> Add utility attributes to get camera data
